### ISSUE TITLE
Where's the capability for .fx files?

### ISSUE THREAD

**Issue by ChandelureF-5** [MMD-Blender/blender_mmd_tools#23]
I really want to apply shaders and was wondering where this was.

**Comment by UuuNyaa** [comment]
We can't use .fx with Blender yet.
Let's wait for Malt to spread.

> You can use Malt to configure shaders using GLSL.
> I think there is a possibility to port .fx.
> - https://github.com/bnpr/Malt
> - https://github.com/aras-p/hlsl2glslfork
