### ISSUE TITLE
Reset/Toggle Physics

### ISSUE THREAD

**Issue by ghost** [MMD-Blender/blender_mmd_tools#68]
When the body part accidentally penetrate the skirt, it is hard to get the skirt recovered to the correct shape. A trick is to toggle the ``enable physics`` in the MMD software. 

Is there any way to reset the physics to the initial A-pose and re-run the physics computation for a specific frame in blender? One can bake the computed positions into that frame as initials for follow-up frames

**Comment by UuuNyaa** [comment]
This could be accomplished by following methods:
1. Add multiple the same models and building physics in the initial pose of each
2. Add a scene for each initial pose and have rigid body world collections for each scene

The following URL may also be helpful:
https://blender.stackexchange.com/questions/77976/starting-and-stopping-rigid-body-simulations
