### ISSUE TITLE
load .vmd motion onto VRM models

### ISSUE THREAD

**Issue by ghost** [MMD-Blender/blender_mmd_tools#72]
~~https://github.com/UuuNyaa/blender_mmd_tools/issues/35#issuecomment-1113910823~~

~~There is an blender add-on https://github.com/saturday06/VRM_Addon_for_Blender for reading and writing the format. 
And there are some previous attempts to convert VRM  [spring bones](https://github.com/saturday06/VRM_Addon_for_Blender/issues/98)  to PMX rigid-bodies, like https://github.com/wakapippi/VRM2PMXImproved~~

~~I know it would require significant amount of effort to support VMD animations on both formats and conversions between them. Maybe it's easier to have the physics configurations separated for VRM and PMX formats.~~

**Comment by UuuNyaa** [comment]
Thank you for the request.
I will consider a feature to convert VRM models to MMD compatible on [UuuNyaa/blender_mmd_uuunyaa_tools](https://github.com/UuuNyaa/blender_mmd_uuunyaa_tools) .
